apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  default.conf: |-
    server {
      listen       {{ .Values.service.port }};
      server_name  _;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      {{- if .Values.nginxConfig.graphqlRedirectEnabled }}
      location = /graphql {
        proxy_pass http://{{ .Values.nginxConfig.graphqlHost }}:{{ .Values.nginxConfig.graphqlPort }}/graphql;
      }
      {{- end }}

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
