export const enum ObservabilityIconType {
  // These values come from Material. We will replace these with our own icon library in the future.
  Api = 'svg:api',
  Apigee = 'svg:apigee',
  Application = 'device_hub',
  ApplicationFlow = 'svg:application-flow',
  AWS = 'svg:aws',
  AWSRDS = 'svg:aws-rds',
  Backend = 'svg:backend',
  Cassandra = 'svg:cassandra',
  Edge = 'svg:edge',
  Elastic = 'svg:elastic',
  Gateway = 'svg:gateway',
  Helm = 'svg:helm',
  HTTP = 'svg:http',
  JDBC = 'svg:jdbc',
  Kong = 'svg:kong',
  Kubernetes = 'svg:kubernetes',
  MicrosoftAzure = 'svg:microsoft-azure',
  MicrosoftSqlServer = 'svg:microsoft-sql-server',
  Mongo = 'svg:mongo',
  Mysql = 'svg:mysql',
  Node = 'svg:node',
  Oracle = 'svg:oracle',
  PostgreSQL = 'svg:postgre-sql',
  RabbitMQ = 'svg:rabbit-mq',
  Redis = 'svg:redis',
  Serverless = 'svg:serverless',
  Service = 'svg:service',
  ServicesList = 'svg:services-list',
  Tyk = 'svg:tyk'
}
