name: pull-request
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3
      - name: Cache node modules
        uses: actions/cache@v2.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package.json') }}-
            ${{ runner.os }}-node-
      - name: Build
        run: npm run build:ci
        
      - name: Copy unit test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-line-smoothing
          fail_ci_if_error: true
          verbose: true
          flags: unit

      - name: Integration test
        run: ./gradlew jacocoIntegrationTestReport 

      - name: Copy integration test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-line-smoothing
          fail_ci_if_error: true
          verbose: true
          flags: integration

      - name: Archive integration test report
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: /tmp/test-reports
        if: ${{ always() }}
